services:
  coderrank-ui:
    build: ./coderrank-ui
    image: coderrank-ui
    container_name: coderrank-ui
    ports:
      - "3000:3000"
  coderrank-service:
    build: ./coderrank-service
    image: coderrank-service
    container_name: coderrank-service
    volumes:
      - "/home/anurag/codes:/home/codes"
    ports:
      - "5000:5000"
  code-exec-container:
    build: ./code-exec-container
    image: code-exec-container
    container_name: code-exec-container
