services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
  coderrank-ui:
    build: ./coderrank-ui
    image: coderrank-ui
    container_name: coderrank-ui
    ports:
      - "3000:3000"
  coderrank-service:
    build: ./coderrank-service
    image: coderrank-service
    container_name: coderrank-service
    volumes:
      - "/home/anurag/codes:/home/codes"
    ports:
      - "5000:5000"
  code-exec-container:
    build: ./code-exec-container
    image: code-exec-container
    container_name: code-exec-container
  coderrank-db:
    image: postgres
    container_name: coderrank-db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coderrank_db
volumes:
  postgres-data:

